### ISSUE TITLE
Trying to build a pkg from pkgsrc with bmake reports to use bmake to build

### ISSUE THREAD

**Issue by tps800** [Stichting-MINIX-Research-Foundation/minix#67] opened 2015-04-26 10:58 UTC
```
# cd /usr/pkgsrc/net/wget
# bmake
bmake: "/etc/mk.conf" line 4: Please use bmake for pkgsrc instead of the base system make.
```

pkgsrc was snapped Sun Apr 26 14:50:25 CEST 2015 with wget on Windows from github.com, then transfered via scp to minix, unpacked to /usr/pkgsrc using unzip.

The bug seems to be within

```
MAKEVERBOSE?=   1

.if defined(BSD_PKG_MK) && "${PROG:U}" != "pkgin"
.error Please use bmake for pkgsrc instead of the base system make.
.endif
```

`${PROG:U}` seems to expand to bmake, instead to pkgin (I'd expect it to expand to bmake if I am adviced to use bmake). `/etc/mk.conf` is part of the base system.

**Comment by sambuc** [comment] 2015-04-26 11:16
Did you apply the minix patches on that pkgsrc tree? The current ones are available at 
https://github.com/Stichting-MINIX-Research-Foundation/pkgsrc-ng

Without them, it won’t work.

**Comment by tps800** [comment] 2015-04-26 12:56
I've got that from github.com as zip today. I'd think these patches shall be in place as of Sun Apr 26 14:50:25 CEST 2015 (time and date I've got the source packed by github).

**Comment by sambuc** [comment] 2015-10-12 16:58
I finally found the issue.

The problem is caused by a missing  ```/usr/pkg/etc/mk.conf```.

The following should take care of the problem: 
```
cp /usr/pkgsrc/minix/mk.conf.minix /usr/pkg/etc/mk.conf
```

This will be fixed in the next binary repository. 

You might from time to time see failures about ```strip```, to solve this a simple:
```
export STRIP=strip
```
should take care of the problem. I do not have yet a permanent solution for this.

If this solves your problem, please close this issue.


Regards,

Lionel

**Comment by dcvmoole** [comment] 2017-05-08 11:34
After well over a year we have still not received the input needed to continue working on this issue. Therefore I am closing it. Please feel free to reopen it with more information, though.

**Closed by dcvmoole** 2017-05-08 11:34 UTC
