### ISSUE TITLE
htop as in the repositories dumps core

### ISSUE THREAD

**Issue by tps800** [Stichting-MINIX-Research-Foundation/minix#59] opened 2015-04-10 12:59 UTC
install htop:

``` shell
# pkgin in htop
```

next call htop:

``` shell
# htop
[1]   Segmentation fault (core dumped) htop
```

necessary libraries are installed:

``` shell
# pkgin requires htop
Files required by htop-1.0.1:
        /usr/pkg/lib/libncursesw.so.5
        /usr/lib/libm.so.0
        /usr/lib/libc.so.12
```

all are available.

**Comment by GReagle** [comment] 2015-11-06 13:48
I can reproduce this bug using minix_R3.3.0-588a35b.iso using qemu/kvm.  I am interested in investigating whether I can debug it.  Do I need to use a later version of Minix (i.e. "Tracking Current") for my debugging efforts?

**Comment by dcvmoole** [comment] 2015-11-06 14:31
Hello! Yes, using the latest minix sources is always a good idea, as minix is still constantly changing; otherwise, in the worst case you might end up debugging something that has already been solved. However, two things that I think are useful to know here. 1) Right now we are preparing for a new release, which will include base system and pkgsrc updates that are not merged yet but likely relevant, and as such you *may* want to wait (an estimated (no hard promises!)) two weeks and start from the new release instead, just to make things easier. 2) I did take a quick look by running htop through trace(1) and it seemed to crash right after failing to open a particular /proc file, which is likely part of NetBSD's Linux emulation. We do not have such emulation nor do we have plans on adding support for Linux emulation at this time, since we will still be working on getting native NetBSD stuff to work for quite a while first. *If* htop does not have the ability to use NetBSD's own primitives for getting process (etc) information, getting it to work on MINIX3 may be less than trivial. With that said, we would of course love to have htop working since it's seriously cool :) and we wholeheartedly welcome your efforts to look into this! Any insights on what is missing for getting it to work are appreciated as well..

**Comment by GReagle** [comment] 2015-11-06 19:22
I cannot find trace (which I've enver used before) on minix 3.3.0.  Not pre-installed, not in 'pkgin avail'.

**Comment by dcvmoole** [comment] 2015-11-06 23:08
The trace utility was indeed added after the 3.3.0 release, and part of minix-current.

**Comment by tcort** [comment] 2016-02-09 13:20
I tried `htop` on Minix 3.4.0 RC2. Still get a segmentation fault.

I ran a trace and it crashes just after failing to read [/proc/stat](http://www.linuxhowtos.org/System/procstat.htm). The `htop` [download page](http://hisham.hm/htop/index.php?page=downloads) has the following message:

> htop 1.0.3 is Linux only, but the upcoming version (currently on Git) also runs on FreeBSD, OpenBSD and Mac OS X. Stay tuned for the next release!

I tried compiling the latest version from [git](https://github.com/hishamhm/htop), but it doesn't compile. There are platform specific directories (about 1000 lines of code per platform) as well as an `unsupported` platform directory. The `unsupported` platform hasn't been compiled lately and seems to be lacking a few variables, and the types aren't always what they should be. The software also assumes `ncurses` is built with general purpose mouse support which Minix `ncurses` is not built with.

**Comment by dcvmoole** [comment] 2017-05-08 11:21
Now that we have added sysctl support, and NetBSD's ps/top work out of the box on MINIX, there should be no reason to add MINIX-specific support to htop anymore. The way forward here is to wait until 1) htop is extended with NetBSD support, 2) pkgsrc imports a new enough version of htop to include the NetBSD support, and 3) we resync to a new enough pkgsrc tree. At that point we can see if we need to make additional system changes to MINIX to support the NetBSD port of htop. Anyone interested in working on this item is encouraged to look into adding NetBSD support to htop (ie the first point). As such it is no longer a MINIX issue, and I am closing this for now.

**Closed by dcvmoole** 2017-05-08 11:21 UTC
Labels: pkgsrc
