### ISSUE TITLE
isoread doesn't work

### ISSUE THREAD

**Issue by blakemcbride** [Stichting-MINIX-Research-Foundation/minix#13] opened 2014-12-28 22:18 UTC
Using isoread under 3.3.0 trying to copy a file from a CD/DVD to the local file system - it copied the file without any reported errors.  The file is the right size but the MD5 is wrong.

**Comment by dcvmoole** [comment] 2015-08-15 12:57
I cannot reproduce this: taking /netbsd from a NetBSD 6.1.4 ISO image (that I had lying around) results in the same MD5 sum through both isofs and isoread. Could you please provide more details on what ISO and file you used, and how you obtained both the actual and the reference MD5 sum?

**Comment by dcvmoole** [comment] 2017-05-08 11:03
After well over a year we have still not received the input needed to continue working on this issue. Therefore I am closing it. Please feel free to reopen it with more information, though.

**Closed by dcvmoole** 2017-05-08 11:03 UTC
Labels: bug, input needed, userland
