### ISSUE TITLE
wget not working (msg: libidn: warning: libiconv not installed, cannot convert data to UTF-8)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Stichting-MINIX-Research-Foundation/minix#30] opened 2015-03-11 10:59 UTC
![wget](https://cloud.githubusercontent.com/assets/642286/6594952/db396c04-c7e5-11e4-8ee0-5f48bfb3e8d7.png)
1. see pic above please
2. e.g. downloading via "curl -O url" works fine

I'm using
wget-1.15nb1
and have installed already libidn-1.28 + libiconv-1.14.nb2

minix 3.3.0-588a35b inside virtualbox 4.3.24

**Comment by tps800** [comment] 2015-04-10 12:47
Same here. Looks like libidn does not load libiconv libraries any assumes UTF-8 names. Maybe libidn wasn't build with libiconv support?

**Comment by dcvmoole** [comment] 2015-04-10 13:18
That is just a warning though, the real problem is the "Read error (Function not implemented)" bit. IIRC wget used some flag on recv() that we don't support - MSG_PEEK or so? Solving this is going to require a patch against wget, as it has before..

**Comment by tps800** [comment] 2015-04-10 13:25
Maybe it is enough to compile the latest version available on http://ftp.gnu.org/gnu/wget/? It is version 1.16.3.

**Comment by dcvmoole** [comment] 2015-04-10 13:39
I'm not sure if it would help for this case, but in general we try to avoid doing that altogether: given the limited resources of the minix3 project, it is in our interest to fork as little of the upstream pkgsrc repository as possible. As such, a minix3-specific patch against the wget version in pkgsrc might actually be a cleaner way to resolve the problem either way..

**Comment by tps800** [comment] 2015-04-26 10:44
pkgsrc for wget was checked in 9 months ago. At the moment pkgsrc snapshot from NetBSD is at 2015Q2. Newer versions are inside. Could it be an idea importing NetBSD pkgsrc on a regular base? Only adding in patches for minix3? As it is done by Debian/kfreeBSD for kernel sources?

**Comment by antoineL** [comment] 2015-04-27 06:53
On 2015-04-26 10:44Z, Thomas wrote:
> pkgsrc for wget was checked in 9 months ago. At the moment pkgsrc
> snapshot from NetBSD is at 2015Q2. Newer versions are inside.

That problem is bigger as you seem to think: the synchronisation with
NetBSD "src" tree is dated around November 2013, that's 18 months ago.


> Could it be an idea importing NetBSD pkgsrc on a regular base?
> Only adding in patches for minix3?

It is an idea... and a lot of work. This was the plan, of course.
Over the past years, the number of patches for MINIX-specific issues has
dropped significantly. However, they are still a number of them :-(


> As it is done by Debian/kfreeBSD for kernel sources?

Sorry? AFAIK there is no FreeBSD thing within kernel, and much less Debian.


Antoine

**Comment by dcvmoole** [comment] 2017-05-08 11:10
I believe it is fair to say that the core of this issue ("wget not working") has been misidentified as revolving around libidn/libiconv in this thread. The reason that wget did not work was the "Read error (Function not implemented)" error in the screenshot, which was caused by an altogether different issue (namely, missing functionality in the network stack). That issue has now been resolved in minix-current. wget will currently still complain about libidn/libiconv, but the download will work. As such I am closing this issue. However, please feel free to open another issue if the libidn/libiconv problem does cause real problems in some other wget use case.

**Closed by dcvmoole** 2017-05-08 11:10 UTC
Labels: pkgsrc
